literally regex command event lol
Discord-Bot-Builder/blocks pull request #2
Opened 2021-01-07 23:24 UTC by choke-dev

basically runs if it detects a word specified

2021-01-11 10:47 UTC, Dad-Ju submitted a review, later dismissed
Could you add some Comments to the Regex Stuff ? 
The later You will love it :D

(Not Tested yet!)

2021-01-23 14:42 UTC, ACertainCoder requested changes
Please also make sure to move the block into the blocks folder

2021-01-23 14:58 UTC, ACertainCoder commented
Tip: I would rather use
```js
for (const commandName of Object.keys(slowmodeData)) {
    const userIDs = slowmodeData[commandName];
    ...
}
```
or
```js
for (const userIDs of Object.values(slowmodeData)) {
    ...
}
```
instead of
```js
for (const commandName in slowmodeData) {
    const userIDs = slowmodeData[commandName];
    ...
}
```
because `for..of` loops through the prototypes of an object too. This can cause slowdowns or maybe even unexpected errors. `Object.keys` and `Object.values` both return an array which is much easier to loop through.

2021-01-27 07:36 UTC, choke-dev commented
block was moved to the blocks folder.

2021-01-28 09:16 UTC, choke-dev reviewed
fixed the incorrect file path also edited code

2021-01-28 11:35 UTC, choke-dev reviewed
moved it to the blocks folder

2021-01-28 19:49 UTC, ACertainCoder requested changes
There are a few more things that need to be changed but everything else is perfectly fine. I'll test the block once more after these issues are solved and approve it then.

2021-01-28 19:49 UTC, ACertainCoder commented on blocks/regex_command_event.js
> +            "description": "Acceptable Types: Text, Unspecified\n\nDescription: Expression Example: i (case isensitive) g (global) (Default: ig)",
Needs to be changed to "insensitive"

2021-01-28 19:49 UTC, ACertainCoder commented on blocks/regex_command_event.js
> +            "id": "case_sensitive",
Case sensitivity can be controlled via the regex expression, this option can be removed.

2021-01-28 19:49 UTC, ACertainCoder commented on blocks/regex_command_event.js
> +                for (const userID in userIDs) {
for ... of Object.keys(...)

2021-01-28 19:49 UTC, ACertainCoder commented on blocks/regex_command_event.js
> +                    for (const discordID in discordIDs) {
for ... of Object.keys(...)

2021-01-29 23:01 UTC, ACertainCoder commented on blocks/regex_command_event.js
> +            "description": "Acceptable Types: Text, Unspecified\n\nDescription: Expression Example: i (case isensitive) g (global) (Default: ig)",
You need to change "case **i**sensitive" to "case **in**sensitive".

2021-01-29 23:02 UTC, ACertainCoder commented on blocks/regex_command_event.js
> +            "id": "case_sensitive",
As already said, you can remove this option entirely.

2021-08-17 03:41 UTC, closed without merging