Collection of Mods
Discord-Bot-Builder/blocks pull request #4
Opened 2021-01-07 23:36 UTC by MrMcyeet

Just a bunch of mods that ive made/modified.

2021-01-11 11:22 UTC, Dad-Ju requested changes
Here is some Stuff to do 
Please check over all Indents and stuff like this (code style)

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/Switch_conditional.js
> +        if (operation == "equal") {
please check code style (indents usw)

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/better_send_message_with_text.js
> +        .catch(() => this.RunNextBlock("action2", cache));
add a error message output if you have the error action

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/better_send_message_with_text[x20].js
> +    name: "Better Send Message with text[x20]",
please remove "[ ]" from Filename

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/better_send_message_with_text[x20].js
> +    description: "Sends a message with built in text block.\nThis was modified to add the ability to type text directly into the block, and allow 4x placeholders (i.e. ${text1}, ${text2}, etc..)",
this allows x20 and not x4 :)

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/better_send_message_with_text[x20].js
> +        s = s.replace (/(\${text1})|(\${text2})|(\${text3})|(\${text4})|(\${text5})|(\${text6})|(\${text7})|(\${text8})|(\${text9})|(\${text10})|(\${text11})|(\${text12})|(\${text13})|(\${text14})|(\
what about 
```let s = eval("`" + text.replace(/`/g, "\\`") + "`")``` ?
thats why we implememnt it with `${var}` and the abillity to get keys is also given

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/better_send_message_with_text.js
> +        s = s.replace (/(\${text1})|(\${text2})|(\${text3})|(\${text4})/g, m => chars[m]);
same like x20

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/generate_random_number.js
> +		const number = Math.floor(Math.random() * (max_number - min_number + 1)) + min_number
fix this indent please

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/generate_random_number.js
> +    description: "Generates a random number.\nModified to actually take into account of the min and max values supplied.",
remove the modified .... stuff and send it to gold as fix ^^

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/get_message_info.js
> +            case 36:
Im just asking why ? 
What about get Message Arguments Block ?
it would be more usefull there

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/run_javascript_code_5xMOD.js
> +            const {performance} = require("perf_hooks");
use await this.require("...") please

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/run_javascript_code_5xMOD.js
> +        const evaluation = javascript_code => {
something is wrong her.  what do you want to achieve ?

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/Switch.js
> +    name: "Get state code",
I thing your file has the false naming

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/Switch_conditional.js
> +    name: "Switch (conditional)",
start Filename with lowercase please

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/state_codes.js
> +    name: "Get state code",
same as "Switch.js" ?

2021-01-11 11:22 UTC, Dad-Ju commented on blocks/better_send_message_with_text[x20].js
> +    name: "Better Send Message with text[x20]",
please also for all other files

2021-09-29 22:01 UTC, NotCallMeHacker commented on blocks/Switch_conditional.js
> +        if (operation == "equal") {
no u

2023-03-12 17:49 UTC, ACertainCoder commented
Closing this as it's inactive.

2023-03-12 17:49 UTC, closed without merging